NUMPY ARRAYS

In [82]:
num =[1,2,3,4]

importing numpy package to use 

In [83]:
import numpy as np

In [84]:
np.array(num)

array([1, 2, 3, 4])

np.array() converts the datatype into list 

In [85]:
my_matrx = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [86]:
np.array(my_matrx)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

The above list has been converted 2 dimensional array, it has two set of'[]' brackets to indicate the 2 dimensional array

lets see few BUILTIN FUNCTIONS in NUMPY

In [87]:
 np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(start value,stop value - 1) is same like range but provides a array, we can also provide STEP SIZE - difference of values  as third argument

In [88]:
 np.arange(0,11,3) 

array([0, 3, 6, 9])

we can use np.zeros() as vectors in one dimension and provide values in tuples as two dimension np.zeros((4,4)) with values ZERO, first number represent rows and second number represent columns

In [89]:
np.zeros(3)

array([0., 0., 0.])

In [90]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [92]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

LINSPACE() ,linspace(start_value, stop_value,Evenly_spaced_points) it might looks same like arange(start,stop,steps) but has different funcions, arange provides difference of value from the start and stop value but linspace provide a evenly spaced points between that values(ALWAYS CHECK '[]' for dimensions)

In [209]:
np.linspace(0,.1,10)

array([0.        , 0.01111111, 0.02222222, 0.03333333, 0.04444444,
       0.05555556, 0.06666667, 0.07777778, 0.08888889, 0.1       ])

In [94]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

IDENTITY MATRIX IN NUMPY

In [95]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

RANDOM.RAND() provides a random values of a  uniformly distributed values from 0 to 1, we dont pass tuple for two dimension in this

In [96]:
np.random.rand(5)

array([0.02193526, 0.11305584, 0.79645065, 0.04161425, 0.67183283])

In [97]:
np.random.rand(3,4)

array([[0.3844015 , 0.81342867, 0.92957777, 0.45181161],
       [0.17310321, 0.12599893, 0.1779204 , 0.42097158],
       [0.13764409, 0.80812397, 0.50862832, 0.01761729]])

RANDOM.RANDN() provides a random values of a  standard normal distribution valued around 0, we dpnt pass tuple for two dimension in this

In [98]:
np.random.randn(5)

array([ 0.55744764, -3.6831231 ,  1.37453449,  1.4057701 ,  0.05823904])

In [99]:
np.random.randn(3,3)

array([[ 1.49526085, -0.16581019, -2.79716915],
       [-0.71512196, -0.81358064,  0.46423348],
       [ 0.70183873, -1.11271577,  0.08990435]])

randint(lowvalue,highvalue)   lowvalue is inclusive and high value is excluded, third argument can be added as the number of random elements needed

In [100]:
np.random.randint(1,100)

12

In [101]:
np.random.randint(1,100,10)

array([21, 56, 17,  5, 17, 32, 81, 49,  5, 49])

In [102]:
arr = np.arange(25)

In [103]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

We can reshape the array dimension using ARRAY_NAME.RESHAPE.(N , N), first find the lenth  of the array and Dimension and then use the correct (N X N) size 

In [104]:
 len(arr)

25

In [105]:
arr.shape 

(25,)

In [106]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 25 into shape (3,3)

In [107]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

returns error if the size is not a correct fit

In [108]:
arr.max()

24

In [109]:
arr.min()

0

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

if We want to find the location of the max or min element, we use ARG

In [111]:
arr.argmax()

24

In [112]:
arr.argmin()

0

let's play around 

In [113]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [114]:
arr.shape

(25,)

In [115]:
arr = arr.reshape(5,5)

In [116]:
arr.shape

(5, 5)

In [117]:
arr.dtype 

dtype('int32')

NUMPY INDEXING AND SLICING

In [118]:
arr = np.arange(11)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

ARRAY SLICING is a important concept, for example when  we can create a slice of org_array(part of array and assign it to new variable) and provides it value in new_array, it acually creates a link to that  org_array so whatever changes made in new_array will affect the org_array

In [121]:
Slice_arr = arr[0:6]

In [122]:
Slice_arr

array([0, 1, 2, 3, 4, 5])

In [123]:
Slice_arr[:] = 100

In [124]:
Slice_arr

array([100, 100, 100, 100, 100, 100])

In [125]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

changes made in the Slice_arr affects the arr, so we have to use COPY() to specifically indicate that we are copying the array and dont want it be a link 

In [126]:
arr_cpy = arr.copy()

In [127]:
arr_cpy

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [128]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [129]:
arr_cpy[:] = 100

In [130]:
arr_cpy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

Changes made in the arr_cpy are not affected in arr

ARRAY INDEXING 

We ca use a[1][2] or a[1,2] and same like list or array we can use   ':' for indexing 

In [134]:
arr = np.arange(16)

In [137]:
arr = arr.reshape(4,4)

In [ ]:
arr 

In [140]:
arr[1][2]

6

In [141]:
arr[1,2]

6

In [142]:
arr[1:3,2:]

array([[ 6,  7],
       [10, 11]])

CONDITIONAL INDEXING 

In [147]:
Cond_arr = np.arange(1,11)

In [151]:
Cond_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
bool_array = Cond_arr>5

In [150]:
bool_array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

we can check the conditions and return values, we can directly use in single line 

In [153]:
Cond_arr[Cond_arr>5]

array([ 6,  7,  8,  9, 10])

In [154]:
Cond_arr[bool_array]

array([ 6,  7,  8,  9, 10])

 We can use functions together  

In [170]:
func_func = np.arange(16).reshape(4,4)

In [171]:
func_func

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

 We can change the 2 dimension array to 1 dimension array using STR and FLATTEN,

In [186]:
arr = np.arange(16)

In [187]:
np.array(arr)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [188]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
arr = str(arr.flatten())

In [190]:
arr

'[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]'

 NUMPY OPERATIONS

* ARRAY WITH ARRAY
* ARRAY WITH SCALARS
* UNIVERSAL ARRAY FUNCTIONS

In [193]:
arr = np.arange(16)

In [194]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [195]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [196]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [197]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225], dtype=int32)

Shows error for not possible operations, nan - null,inf=infinity 

 Warning on division by zero, but not an error!
 Just replaced with nan
 arr/arr

In [198]:
arr/arr

C:\Users\virambab\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

 Also warning, but not an error instead infinity
1/arr

In [199]:
1/arr

C:\Users\virambab\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667])

In [200]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [202]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [203]:
np.max(arr)

15

In [204]:
arr.max()

15

In [206]:
arr.argmin()

0

In [207]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

to perform column or row additon sub mul etc, axis = 0 represents column and axis =1 or -1 represents row

In [211]:
arr.sum(axis = 0)

120

In [ ]:
use this link to follow other universal array builtin functions in Numpy 
http://docs.scipy.org/doc/numpy/reference/ufuncs.html